### PR TITLE
Create README

### PR DESCRIPTION
**Pull request by Pugabyte**
This is a semi-basic README with setup instructions, compilation instructions and a link to the discord.

### CODE REVIEW

**Comment by WheezyGold7931** [comment]
Needs Gradle depends listed but that's up to @iBlitzkriegi

**Comment by WheezyGold7931** [comment]
Otherwise looks fine to merge

**Comment by Pugabyte** [comment]
I was planning on making the gradle setup better in a different PR, but after talking with Blitz I think ill let him do that using njol's repo (pls blitz)

**Comment by Snow-Pyon** [comment]
You should link the documentation or the site of Vixio itself:
http://vixio.space/

**Pull request merged**
